name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 3 * * 0" # every Sunday at 3am

env:
  CI: true

jobs:
  own_tests:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    name: "Own Tests"
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - run: yarn install --frozen-lockfile
      - run: yarn jest

  # tests:
  #   if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
  #   name: "Test: ${{ matrix.name }}"
  #   timeout-minutes: 5
  #   runs-on: ubuntu-latest
  #   continue-on-error: ${{ matrix.allow-failure }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       name:
  #         - 'emberclear'
  #         - 'highlightjs-glimmer'
  #         - 'limber'
  #       allow-failure: [true]
  #       # include:
  #       #   - name: emberclear
  #       #     allow-failure: true
  #       #   - name: highlightjs-glimmer
  #       #     allow-failure: true
  #       #   - name: limber
  #       #     allow-failure: true

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: volta-cli/action@v1
  #     - run: yarn install --frozen-lockfile
  #     - run: ./partner-tests/${{ matrix.name }}.sh

  # https://github.com/changesets/action
  release:
    name: Release
    timeout-minutes: 5
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - own_tests

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: ./.github/actions/pnpm
      - uses: ./.github/actions/download-built-package
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

