name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 3 * * 0" # every Sunday at 3am

env:
  CI: true

jobs:
  own_tests:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    name: "Own Tests"
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1
      - run: yarn install --frozen-lockfile
      - run: yarn jest

  # tests:
  #   if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
  #   name: "Test: ${{ matrix.name }}"
  #   timeout-minutes: 5
  #   runs-on: ubuntu-latest
  #   continue-on-error: ${{ matrix.allow-failure }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       name:
  #         - 'emberclear'
  #         - 'highlightjs-glimmer'
  #         - 'limber'
  #       allow-failure: [true]
  #       # include:
  #       #   - name: emberclear
  #       #     allow-failure: true
  #       #   - name: highlightjs-glimmer
  #       #     allow-failure: true
  #       #   - name: limber
  #       #     allow-failure: true

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: volta-cli/action@v1
  #     - run: yarn install --frozen-lockfile
  #     - run: ./partner-tests/${{ matrix.name }}.sh

  ember-cli-update:
    if: github.event_name == 'pull_request' && github.event.pusher.name == 'renovate-bot'
    runs-on: ubuntu-latest
    needs:
      # - tests
      - own_tests

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GitHubToken }}
      - uses: actions/setup-node@v3
      - uses: kellyselden/ember-cli-update-action@v3
        with:
          autofix_command: yarn lint:fix
          ignore_to: true

  publish:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    needs:
      # - tests
      - own_tests

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: volta-cli/action@v1
      - run: yarn install

      - name: Release
        run: yarn semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
