name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 3 * * 0' # every Sunday at 3am

env:
  CI: true

jobs:
  own_tests:
    name: 'Own Tests'
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: ./.github/actions/pnpm
      - run: pnpm test

  lint_source:
    name: Lint Source
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: ./.github/actions/pnpm

      - name: Formatting
        run: pnpm format

      - name: ESLint
        run: pnpm lint:js

  lint_test-packages:
    name: Lint Test Packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: ./.github/actions/pnpm

      - name: ESLint
        run: pnpm lint:all:js

  lint_formatting:
    name: Lint Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: ./.github/actions/pnpm


  # lint_types:
  #   name: Lint Types
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: volta-cli/action@v4
  #     - uses: ./.github/actions/pnpm

  #     - name: Type Check
  #       run: pnpm tsc
